-- eliminar tablas que no tienen clave foránea

DROP TABLE IF EXISTS DETALLE_COMPRA;
DROP TABLE IF EXISTS COMPRA_PRODUCTO;
DROP TABLE IF EXISTS VENTA;
DROP TABLE IF EXISTS ACCESORIO;
DROP TABLE IF EXISTS INSTRUMENTO;
DROP TABLE IF EXISTS TIPO_INSTRUMENTO;
DROP TABLE IF EXISTS SUBTIPO;
DROP TABLE IF EXISTS MARCA;
DROP TABLE IF EXISTS CARRITO;

-- Elimina las tablas que tienen restricciones de clave foránea hacia otras tablas

DROP TABLE IF EXISTS DETALLE_RETIRO;
DROP TABLE IF EXISTS DETALLE_DESPACHO;
DROP TABLE IF EXISTS DETALLE_FACTURA;

-- elimina las tablas restantes

DROP TABLE IF EXISTS RETIRO;
DROP TABLE IF EXISTS DESPACHO;
DROP TABLE IF EXISTS TIPO_ENVIO;
DROP TABLE IF EXISTS BODEGUERO;
DROP TABLE IF EXISTS BODEGA;
DROP TABLE IF EXISTS VENDEDOR;
DROP TABLE IF EXISTS TIENDA;
DROP TABLE IF EXISTS EMPLEADO;
DROP TABLE IF EXISTS TIPO_EMPLEADO;
DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS COMUNA;
DROP TABLE IF EXISTS CIUDAD;
DROP TABLE IF EXISTS REGION;
DROP TABLE IF EXISTS PRODUCTO;


CREATE TABLE REGION (
    ID_REGION INT PRIMARY KEY,
    NOMBRE_REG VARCHAR(80) NOT NULL
);

CREATE TABLE CIUDAD(
    ID_CIUDAD INT PRIMARY KEY,
    NOM_CIUD VARCHAR(80) NOT NULL, 
    ID_REGION INT,
    CONSTRAINT FK_CIUDAD_REGION FOREIGN KEY (ID_REGION) REFERENCES REGION(ID_REGION)
);

CREATE TABLE COMUNA(
    ID_COM INT PRIMARY KEY,
    NOM_COM VARCHAR(100) NOT NULL,
    ID_CIUDAD INT,
    ID_REGION INT,
    CONSTRAINT FK_COMUNA_CIUDAD FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDAD(ID_CIUDAD),
    CONSTRAINT FK_COMUNA_REGION FOREIGN KEY (ID_REGION) REFERENCES REGION(ID_REGION)
);

CREATE TABLE ROL (
  ID_ROL INT PRIMARY KEY, -- 1 PARA ADMIN, 2 PARA USUARIO
  NOMBRE_ROL VARCHAR(50)
);

CREATE TABLE ADMINISTRADOR (
    RUT_ADM VARCHAR(8) PRIMARY KEY,
    DV_ADM CHAR(1) NOT NULL,
    NOM_ADM VARCHAR(80) NOT NULL,
    APAT_ADM VARCHAR(50) NOT NULL,
    AMAT_ADM VARCHAR(50) NOT NULL,
    FECHA_NAC_ADM DATE NOT NULL,
    DIRECCION_ADM VARCHAR(100) NOT NULL,
    EMAIL_ADM VARCHAR(100) NOT NULL,
    CONTRASEÑA VARCHAR(6) NOT NULL,
    ID_ROL INT, 
    ID_COM INT,
    ID_CIUDAD INT,
    ID_REGION INT,
    CONSTRAINT FK_ADMINISTRADOR_ROL FOREIGN KEY (ID_ROL) REFERENCES ROL(ID_ROL),
    CONSTRAINT FK_ADMINISTRADOR_COMUNA FOREIGN KEY (ID_COM) REFERENCES COMUNA(ID_COM),
    CONSTRAINT FK_ADMINISTRADOR_CIUDAD FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDAD(ID_CIUDAD),
    CONSTRAINT FK_ADMINISTRADOR_REGION FOREIGN KEY (ID_REGION) REFERENCES REGION(ID_REGION)

);

CREATE TABLE CLIENTE(
    RUT_CLI VARCHAR(8) PRIMARY KEY,
    DV_CLI CHAR(1) NOT NULL,
    NOM_CLI VARCHAR(80) NOT NULL,
    APAT_CLI VARCHAR(50) NOT NULL,
    AMAT_CLI VARCHAR(50) NOT NULL,
    FECHA_NAC_CLI DATE NOT NULL,
    DIRECCION_CLI VARCHAR(100) NOT NULL,
    EMAIL_CLI VARCHAR(100) NOT NULL,
    CONTRASEÑA VARCHAR(6) NOT NULL,
    ID_ROL INT DEFAULT 2,
    ID_COM INT,
    ID_CIUDAD INT,
    ID_REGION INT,
    CONSTRAINT FK_CLIENTE_ROL FOREIGN KEY (ID_ROL) REFERENCES ROL(ID_ROL),
    CONSTRAINT FK_CLIENTE_COMUNA FOREIGN KEY (ID_COM) REFERENCES COMUNA(ID_COM),
    CONSTRAINT FK_CLIENTE_CIUDAD FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDAD(ID_CIUDAD),
    CONSTRAINT FK_CLIENTE_REGION FOREIGN KEY (ID_REGION) REFERENCES REGION(ID_REGION)
    
);

CREATE TABLE TIPO_EMPLEADO(
    COD_TIPO_EMP CHAR(1) PRIMARY KEY,
    DESC_TIPO_EMP VARCHAR(30) NOT NULL   
     
);

CREATE TABLE EMPLEADO(
    RUT_EMP VARCHAR(8) PRIMARY KEY, 
    DV_EMP CHAR(1) NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    APATERNO_EMP VARCHAR(50) NOT NULL,
    AMATERNO_EMP VARCHAR(50) NOT NULL,
    FECHA_NAC DATE NOT NULL,
    DIRECCION VARCHAR(100) NOT NULL,
    EMAIL_EMP VARCHAR(100) NOT NULL,
    SALARIO DECIMAL(10, 2) NOT NULL,
    CONTRASEÑA VARCHAR(8) NOT NULL,
    COD_TIPO_EMP CHAR(1),
    ID_COM INT,
    ID_CIUDAD INT,
    ID_REGION INT,
    CONSTRAINT FK_EMPLEADO_TIPO_EMPLEADO FOREIGN KEY (COD_TIPO_EMP) REFERENCES TIPO_EMPLEADO(COD_TIPO_EMP),
    CONSTRAINT FK_EMPLEADO_COMUNA FOREIGN KEY (ID_COM) REFERENCES COMUNA(ID_COM),
    CONSTRAINT FK_EMPLEADO_CIUDAD FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDAD(ID_CIUDAD),
    CONSTRAINT FK_EMPLEADO_REGION FOREIGN KEY (ID_REGION) REFERENCES REGION(ID_REGION)
    
);

CREATE TABLE TIENDA(
    ID_TIENDA INT PRIMARY KEY,
    NOMBRE_TIENDA VARCHAR(100) NOT NULL,
    DIR_TIENDA VARCHAR(100) NOT NULL,
    ID_COM INT,
    ID_CIUDAD INT,
    ID_REGION INT,    
    CONSTRAINT FK_TIENDA_COMUNA FOREIGN KEY (ID_COM) REFERENCES COMUNA(ID_COM),
    CONSTRAINT FK_TIENDA_CIUDAD FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDAD(ID_CIUDAD),
    CONSTRAINT FK_TIENDA_REGION FOREIGN KEY (ID_REGION) REFERENCES REGION(ID_REGION)
);

CREATE TABLE VENDEDOR(
    ID_VENDEDOR INT PRIMARY KEY,
    RUT_EMP VARCHAR(8),
    ID_TIPO_EMP INT(2),
    VENTAS INT NOT NULL,
    ID_TIENDA INT,
    CONSTRAINT FK_VENDEDOR_EMPLEADO FOREIGN KEY (RUT_EMP) REFERENCES EMPLEADO(RUT_EMP),
    CONSTRAINT FK_VENDEDOR_TIPO_EMPLEADO FOREIGN KEY (ID_TIPO_EMP) REFERENCES TIPO_EMPLEADO(ID_TIPO_EMP),
    CONSTRAINT FK_VENDEDOR_TIENDA FOREIGN KEY (ID_TIENDA) REFERENCES TIENDA(ID_TIENDA)
);

CREATE TABLE BODEGA(
    ID_BOD INT PRIMARY KEY,
    NOMBRE_BOD VARCHAR(100) NOT NULL,
    DIR_BODEGA VARCHAR(100) NOT NULL,
    ID_COM INT,
    ID_CIUDAD INT,
    ID_REGION INT,
    CONSTRAINT FK_BODEGA_COMUNA FOREIGN KEY (ID_COM) REFERENCES COMUNA(ID_COM),
    CONSTRAINT FK_BODEGA_CIUDAD FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDAD(ID_CIUDAD),
    CONSTRAINT FK_BODEGA_REGION FOREIGN KEY (ID_REGION) REFERENCES REGION(ID_REGION)
);

CREATE TABLE BODEGUERO(
    ID_BODEGUERO INT PRIMARY KEY,
    RUT_EMP VARCHAR(8),
    ID_TIPO_EMP INT(2),
    ID_BOD INT,
    CONSTRAINT FK_BODEGUERO_EMPLEADO FOREIGN KEY (RUT_EMP) REFERENCES EMPLEADO(RUT_EMP),
    CONSTRAINT FK_BODEGUERO_TIPO_EMPLEADO FOREIGN KEY (ID_TIPO_EMP) REFERENCES TIPO_EMPLEADO(ID_TIPO_EMP),
    CONSTRAINT FK_BODEGUERO_BODEGA FOREIGN KEY (ID_BOD) REFERENCES BODEGA(ID_BOD)
);

CREATE TABLE TIPO_ENVIO(
    COD_TIPO_ENVIO CHAR(1) NOT NULL,
    DESCRIPCION VARCHAR(80) NOT NULL
);

CREATE TABLE DESPACHO(
    ID_DESPACHO INT PRIMARY KEY,
    DESCRIPCION VARCHAR(100) NOT NULL,
    DIRECCION VARCHAR(100) NOT NULL,
    COD_TIPO_ENVIO CHAR(1),
    ID_BOD INT, 
    CONSTRAINT FK_DESPACHO_TIPO_ENVIO FOREIGN KEY (COD_TIPO_ENVIO) REFERENCES TIPO_ENVIO(COD_TIPO_ENVIO),
    CONSTRAINT FK_DESPACHO_BODEGA FOREIGN KEY (ID_BOD) REFERENCES BODEGA(ID_BOD)
);

CREATE TABLE RETIRO(
    ID_RETIRO INT PRIMARY KEY,
    DESCRIPCION VARCHAR(100) NOT NULL,
    ID_TIENDA INT,
    ID_TIPO_ENV INT(1),
    CONSTRAINT FK_RETIRO_TIENDA FOREIGN KEY (ID_TIENDA) REFERENCES TIENDA(ID_TIENDA),
    CONSTRAINT FK_RETIRO_TIPO_ENVIO FOREIGN KEY (ID_TIPO_ENV) REFERENCES TIPO_ENVIO(ID_TIPO_ENV)
);



CREATE TABLE MARCA(
    ID_MARCA INT(2) PRIMARY KEY,
    NOMBRE_MARCA VARCHAR(60) NOT NULL
);

CREATE TABLE SUBTIPO(
    ID_SUBTIPO INT(1) PRIMARY KEY,
    NOMBRE_SUBTIPO VARCHAR(60) NOT NULL,
    ID_MARCA INT(2),
    CONSTRAINT FK_SUB_TIPO FOREIGN KEY (ID_MARCA) REFERENCES MARCA(ID_MARCA)
);


CREATE TABLE INSTRUMENTO(
    ID_INSTR INT PRIMARY KEY,
    NOMBRE_INSTR VARCHAR(100) NOT NULL,
    DESCRIPCION_INSTR VARCHAR(100), 
    PRECIO_INSTR INT NOT NULL,
    STOCK_INSTR INT NOT NULL,
    ID_SUBTIPO INT(11),
    CONSTRAINT FK_INSTRUMENTO_SUBTIPO_INSTRUMENTO FOREIGN KEY (ID_SUBTIPO) REFERENCES TIPO_INSTRUMENTO(ID_SUBTIPO)
);

CREATE TABLE ACCESORIO(
    ID_ACCESORIO INT PRIMARY KEY,
    NOMBRE VARCHAR(80) NOT NULL,
    DESCRIPCION VARCHAR(80) NOT NULL,
    PRECIO_ACCE INT NOT NULL,
    STOCK_ACCE INT NOT NULL,
    ID_MARCA INT(2),
    CONSTRAINT FK_ACCESORIO_MARCA FOREIGN KEY (ID_MARCA) REFERENCES MARCA(ID_MARCA)
);


-- veré después

CREATE TABLE PRODUCTO(
    ID_PRODUCTO INT PRIMARY KEY,
    NOMBRE_PROD VARCHAR(100) NOT NULL,
    PRECIO DECIMAL(10, 2) NOT NULL,
    STOCK INT NOT NULL,
    ID_BOD INT,
    CONSTRAINT FK_PRODUCTO_BODEGA FOREIGN KEY (ID_BOD) REFERENCES BODEGA(ID_BOD)
);


CREATE TABLE DETALLE_DESPACHO(
    ID_DETALLE_DESP INT PRIMARY KEY,
    ID_DESPACHO INT,
    ID_PRODUCTO INT,
    CANTIDAD INT NOT NULL,
    CONSTRAINT FK_DETALLE_DESPACHO_DESPACHO FOREIGN KEY (ID_DESPACHO) REFERENCES DESPACHO(ID_DESPACHO),
    CONSTRAINT FK_DETALLE_DESPACHO_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
);

CREATE TABLE DETALLE_RETIRO(
    ID_DETALLE_RETIRO INT PRIMARY KEY,
    ID_RETIRO INT,
    ID_PRODUCTO INT,
    CANTIDAD INT NOT NULL,
    CONSTRAINT FK_DETALLE_RETIRO_RETIRO FOREIGN KEY (ID_RETIRO) REFERENCES RETIRO(ID_RETIRO),
    CONSTRAINT FK_DETALLE_RETIRO_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
);

CREATE TABLE FACTURA(
    NUM_FACTURA INT PRIMARY KEY,
    FECHA DATE NOT NULL,
    MONTO_TOTAL DECIMAL(10, 2) NOT NULL,
    RUT_CLIENTE VARCHAR(12) NOT NULL,
    CONSTRAINT FK_FACTURA_CLIENTE FOREIGN KEY (RUT_CLIENTE) REFERENCES CLIENTE(RUT_CLIENTE)
);

CREATE TABLE DETALLE_FACTURA(
    ID_DETALLE_FACTURA INT PRIMARY KEY,
    NUM_FACTURA INT,
    ID_PRODUCTO INT,
    CANTIDAD INT NOT NULL,
    PRECIO_UNITARIO DECIMAL(10, 2) NOT NULL,
    CONSTRAINT FK_DETALLE_FACTURA_FACTURA FOREIGN KEY (NUM_FACTURA) REFERENCES FACTURA(NUM_FACTURA),
    CONSTRAINT FK_DETALLE_FACTURA_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
);

